[package]
name = "fuse_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exfs = { path = "../exfs"}
env_logger = "0.6.0"
fuser = "0.7"
